# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.auto_nat_dns_proxy = false
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    vb.customize ["modifyvm", :id, "--memory", "256"]
  end

  config.vm.define "tmp-dev" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.240"
        config.vm.hostname = "tmp-dev"
  end

  config.vm.define "tmp-01" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.241"
        config.vm.hostname = "tmp-01"
  end

  config.vm.define "tmp-02" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.242"
        config.vm.hostname = "tmp-02"
  end

  config.vm.define "tmp-03" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.243"
        config.vm.hostname = "tmp-03"
  end

end
