# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.auto_nat_dns_proxy = false
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.define "manage" do |config|
        config.vm.box = "centos66_base"
        config.vm.network :private_network, ip: "192.168.33.2"
        config.vm.hostname = "manage"
  end

  config.vm.define "mon" do |config|
        config.vm.box = "centos66_base"
        config.vm.network :private_network, ip: "192.168.33.3"
        config.vm.hostname = "mon"
  end

end
