# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "storm-dev" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.10"
        config.vm.hostname = "storm-dev"
  end

  config.vm.define "storm-1" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.11"
        config.vm.hostname = "storm-1"
  end

  config.vm.define "storm-2" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.12"
        config.vm.hostname = "storm-2"
  end

  config.vm.define "storm-3" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.13"
        config.vm.hostname = "storm-3"
  end

  config.vm.define "storm-4" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.14"
        config.vm.hostname = "storm-4"
  end

end
