# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "storm1" do |storm1|
        storm1.vm.box = "centos64_minimal"
        storm1.vm.network :private_network, ip: "192.168.33.11"
  end

  config.vm.define "storm2" do |storm2|
        storm2.vm.box = "centos64_minimal"
        storm2.vm.network :private_network, ip: "192.168.33.12"
  end

  config.vm.define "storm3" do |storm3|
        storm3.vm.box = "centos64_minimal"
        storm3.vm.network :private_network, ip: "192.168.33.13"
  end

  config.vm.define "storm4" do |storm4|
        storm4.vm.box = "centos64_minimal"
        storm4.vm.network :private_network, ip: "192.168.33.14"
  end

end
