# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.auto_nat_dns_proxy = false
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.define "yark-dev" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.64"
        config.vm.hostname = "yark-dev"
  end

  config.vm.define "yark-01" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.65"
        config.vm.hostname = "yark-01"
  end

  config.vm.define "yark-02" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.66"
        config.vm.hostname = "yark-02"
  end

  config.vm.define "yark-03" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.67"
        config.vm.hostname = "yark-03"
  end

  config.vm.define "yark-04" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.68"
        config.vm.hostname = "yark-04"
  end

  config.vm.define "yark-pseudo" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.69"
        config.vm.hostname = "yark-pseudo"
  end

end
