# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.auto_nat_dns_proxy = false
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.define "storm2-dev" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.15"
        config.vm.hostname = "storm2-dev"
  end

  config.vm.define "storm2-01" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.16"
        config.vm.hostname = "storm2-01"
  end

  config.vm.define "storm2-02" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.17"
        config.vm.hostname = "storm2-02"
  end

  config.vm.define "storm2-03" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.18"
        config.vm.hostname = "storm2-03"
  end

  config.vm.define "storm2-04" do |config|
        config.vm.box = "centos64_base"
        config.vm.network :private_network, ip: "192.168.33.19"
        config.vm.hostname = "storm2-04"
  end

end
