# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.auto_nat_dns_proxy = false
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  config.vm.define "cass12-dev" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.54"
        config.vm.hostname = "cass12-dev"
  end

  config.vm.define "cass12-01" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.55"
        config.vm.hostname = "cass12-01"
  end

  config.vm.define "cass12-02" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.56"
        config.vm.hostname = "cass12-02"
  end

  config.vm.define "cass12-03" do |config|
        config.vm.box = "centos/7"
        config.vm.network :private_network, ip: "192.168.33.57"
        config.vm.hostname = "cass12-03"
  end

end
