# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "desktop" do |config|
        config.vm.box = "centos65_desktop"
        config.vm.network :private_network, ip: "192.168.33.211"
        config.vm.hostname = "desktop"
	#config.ssh.forward_x11 = true
  end

  config.vm.define "fedora-desk" do |config|
        config.vm.box = "fedora20_desktop"
        config.vm.network :private_network, ip: "192.168.33.212"
        config.vm.hostname = "fedora-desk"
  end

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = true
  
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "3072"]
    vb.customize ["modifyvm", :id, "--vram", "32"]

    vb.auto_nat_dns_proxy = false
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

end

